version: "4.16.3"
services:
  react:
    build:
      context: ./reactapp
    volumes:
      - ./reactapp:/app
    ports:
      - 3000:3000
    image: react:react
    container_name: react_container
    command: npm start
  # user:
  #   build:
  #     context: ./Users
  #   volumes:
  #     - ./Users:/app
  #   DATABASE_URL:
  #   ports:
  #     - 8080:80
  #   image: user:user
  #   container_name: user_container
