FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Users.csproj", "./"]
RUN dotnet restore "./Users.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Users.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Users.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Users.dll"]


# docker build -t calorie -f Dockerfile .
# docker run -ti -p 8080:80 calorie
# Kelvin was here
