FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CalorieTracker.csproj", "./"]
RUN dotnet restore "./CalorieTracker.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CalorieTracker.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "CalorieTracker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CalorieTracker.dll"]


# docker build -t calorie -f Dockerfile .
# docker run -ti -p 8080:80 calorie
# Kelvin was here
